import json

ingredient_data = [
    {"Ingredient": "vitamin d", "Safety_Score": 8, "Comedogenic": False, "Dry_Skin_Safe": True,
     "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Soothing, supports skin repair"},
    {"Ingredient": "water", "Safety_Score": 10, "Comedogenic": False, "Dry_Skin_Safe": True,
     "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Universal solvent; safe and non-irritating"},
    {"Ingredient": "aqua", "Safety_Score": 10, "Comedogenic": False, "Dry_Skin_Safe": True,
     "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Universal solvent; safe and non-irritating"},
    {"Ingredient": "honey", "Safety_Score": 9, "Comedogenic": False, "Dry_Skin_Safe": True,
     "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Natural antibacterial and humectant; soothes and hydrates all skin types"},
    {"Ingredient": "hyaluronic acid", "Safety_Score": 10, "Comedogenic": False, "Dry_Skin_Safe": True,
     "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Deeply hydrating humectant; attracts moisture and plumps skin"},
    {"Ingredient": "salicylic acid", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "BHA exfoliant that unclogs pores and reduces acne"},
    {"Ingredient": "retinol", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Vitamin A derivative; boosts cell turnover but may irritate sensitive skin"},
    {"Ingredient": "niacinamide", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Brightening and anti-inflammatory; strengthens skin barrier and reduces redness"},
    {"Ingredient": "aloe vera", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Soothing and cooling botanical; hydrates and calms irritation"},
    {"Ingredient": "coconut oil", "Safety_Score": 5, "Comedogenic": True,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": False, "Acne_Prone_Safe": False, "Description": "Rich natural moisturizer but highly comedogenic; avoid if acne-prone"},
    {"Ingredient": "benzoyl peroxide", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Powerful acne treatment; kills acne-causing bacteria but may cause dryness"},
    {"Ingredient": "glycolic acid", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "AHA exfoliant that improves texture and clears pores; can be irritating for sensitive skin"},
    {"Ingredient": "tea tree oil", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Natural antibacterial and anti-inflammatory oil; effective for acne but may cause irritation"},
    {"Ingredient": "vitamin k", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Supports skin healing and reduces dark circles and redness"},
    {"Ingredient": "argan oil", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Lightweight natural oil rich in antioxidants; moisturizes without clogging pores"},
    {"Ingredient": "witch hazel", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Astringent and anti-inflammatory; helps tighten pores but may dry out sensitive skin"},
    {"Ingredient": "caffeine", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Reduces puffiness and improves circulation; often used in eye creams"},
    {"Ingredient": "coenzyme q10", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Powerful antioxidant that supports skin repair and reduces signs of aging"},
    {"Ingredient": "chamomile", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Soothing botanical with anti-inflammatory properties; calms sensitive and irritated skin"},
    {"Ingredient": "lactic acid", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Gentle AHA that exfoliates and hydrates; improves texture and supports cell turnover"},
    {"Ingredient": "glycerin", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Humectant that attracts moisture to the skin; safe, non-irritating, and hydrating"},
    {"Ingredient": "jojoba oil", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Skin-mimicking oil that balances sebum and moisturizes without clogging pores"},
    {"Ingredient": "evening primrose oil", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Rich in fatty acids; soothes inflammation and supports hormonal skin balance"},
    {"Ingredient": "shea butter", "Safety_Score": 8, "Comedogenic": True,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": False, "Acne_Prone_Safe": False, "Description": "Rich natural moisturizer with healing properties; can clog pores for acne-prone skin"},
    {"Ingredient": "urea", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Powerful humectant and keratolytic; deeply hydrates and smooths rough skin"},
    {"Ingredient": "peptides", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Short chains of amino acids that support collagen production and skin firmness"},
    {"Ingredient": "propylene glycol", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Common humectant and solvent; helps skin retain moisture and enhances ingredient absorption"},
    {"Ingredient": "rose water", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Soothing and hydrating floral water; helps calm redness and refresh the skin"},
    {"Ingredient": "oregano oil", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Potent natural antimicrobial; can fight acne but may irritate sensitive or dry skin"},
    {"Ingredient": "kojic acid", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Skin-brightening agent that reduces pigmentation; can be irritating for sensitive skin"},
    {"Ingredient": "sorbitol", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Sugar-derived humectant that helps retain moisture and soften the skin"},
    {"Ingredient": "alpha lipoic acid", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Potent antioxidant that helps reduce inflammation and improve skin texture"},
    {"Ingredient": "rosehip oil", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Lightweight oil rich in vitamins A and C; brightens and supports skin regeneration"},
    {"Ingredient": "lavender oil", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Calming essential oil with anti-inflammatory properties; may irritate sensitive or acne-prone skin"},
    {"Ingredient": "phenoxyethanol", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Common preservative used for safety and stability; generally well-tolerated in low concentrations"},
    {"Ingredient": "alpha arbutin", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Gentle skin-brightening ingredient that reduces dark spots and evens out skin tone"},
    {"Ingredient": "squalane", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Non-comedogenic oil that mimics natural skin lipids; lightweight and highly moisturizing"},
    {"Ingredient": "grapeseed oil", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Lightweight antioxidant-rich oil that moisturizes and helps balance oily skin"},
    {"Ingredient": "titanium dioxide", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Mineral UV filter used in sunscreens; provides safe and broad-spectrum sun protection"},
    {"Ingredient": "mandelic acid", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Gentle AHA derived from almonds; exfoliates and brightens without irritation"},
    {"Ingredient": "cetearyl alcohol", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Fatty alcohol that softens and conditions the skin; non-irritating and non-drying"},
    {"Ingredient": "dimethicone", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Silicone-based skin protectant; smooths texture and locks in moisture without clogging pores"},
    {"Ingredient": "zinc oxide", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Mineral sunscreen agent with soothing and antimicrobial properties; ideal for sensitive and acne-prone skin"},
    {"Ingredient": "clary sage oil", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Essential oil with antibacterial and anti-inflammatory properties; may help balance oil but can irritate sensitive skin"},
    {"Ingredient": "sodium hyaluronate", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Salt form of hyaluronic acid; deeply hydrates by attracting moisture into the skin"},
    {"Ingredient": "tartaric acid", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "AHA derived from grapes; gently exfoliates and brightens skin but may cause dryness in sensitive skin"},
    {"Ingredient": "colloidal oatmeal", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Soothing and anti-inflammatory; calms irritation and strengthens the skin barrier"},
    {"Ingredient": "green tea extract", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Potent antioxidant and anti-inflammatory; soothes irritation and helps control oil production"},
    {"Ingredient": "rice bran oil", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Nutrient-rich oil with antioxidants; moisturizes and supports skin elasticity without clogging pores"},
    {"Ingredient": "cocamidopropyl betaine", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Coconut-derived cleansing agent; generally gentle but may cause irritation in very sensitive skin"},
    {"Ingredient": "hemp seed oil", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Non-comedogenic oil rich in omega fatty acids; soothes and balances all skin types"},
    {"Ingredient": "sodium lactate", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Natural humectant derived from lactic acid; hydrates and helps maintain skin’s pH balance"},
    {"Ingredient": "allantoin", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Soothing and skin-conditioning agent; promotes healing and reduces irritation"},
    {"Ingredient": "ferulic acid", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Powerful antioxidant that boosts the stability of vitamins C and E; protects against environmental damage"},
    {"Ingredient": "moringa oil", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Nutrient-rich oil with anti-inflammatory and moisturizing properties; supports skin health without clogging pores"},
    {"Ingredient": "macadamia oil", "Safety_Score": 8, "Comedogenic": True,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": False, "Acne_Prone_Safe": False, "Description": "Rich, emollient oil that deeply nourishes dry skin; may clog pores for oily or acne-prone skin"},
    {"Ingredient": "ceramides", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Essential lipids that strengthen the skin barrier and lock in moisture; ideal for all skin types"},
    {"Ingredient": "borage oil", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Rich in gamma-linolenic acid (GLA); soothes inflammation and supports skin barrier repair"},
    {"Ingredient": "tocopheryl acetate", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Stable form of vitamin E; antioxidant that moisturizes and protects skin from environmental stressors"},
    {"Ingredient": "sodium ascorbate", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Stable, water-soluble form of vitamin C; brightens skin and supports collagen production"},
    {"Ingredient": "arbutin", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Skin-brightening agent that fades dark spots and evens tone; gentle and effective for all skin types"},
    {"Ingredient": "sodium cocoyl isethionate", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Gentle coconut-derived surfactant; cleanses without stripping natural moisture"},
    {"Ingredient": "lactic ferment", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Probiotic-derived ingredient that helps balance skin’s microbiome and improve barrier function"},
    {"Ingredient": "sodium ascorbyl phosphate", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Stable form of vitamin C; brightens skin and helps reduce acne and inflammation"},
    {"Ingredient": "ethylhexyl methoxycinnamate", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Chemical UV filter (also known as octinoxate); protects against UVB rays and is generally well tolerated"},
    {"Ingredient": "meadowfoam seed oil", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Stable, non-comedogenic oil rich in antioxidants; moisturizes and locks in hydration without clogging pores"},
    {"Ingredient": "dandelion extract", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Botanical extract with antioxidant and detoxifying properties; helps soothe and protect skin from pollution"},
    {"Ingredient": "retinaldehyde", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Potent vitamin A derivative; promotes cell turnover and reduces signs of aging and acne, but may cause irritation"},
    {"Ingredient": "ginkgo biloba extract", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Antioxidant-rich botanical extract; improves circulation and protects skin from environmental stressors"},
    {"Ingredient": "pomegranate extract", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Antioxidant-rich botanical that helps protect skin, reduce inflammation, and promote regeneration"},
    {"Ingredient": "licorice root extract", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Brightening and soothing ingredient that reduces redness, evens skin tone, and calms irritation"},
    {"Ingredient": "chia seed oil", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Lightweight oil rich in omega-3 fatty acids; hydrates, soothes, and supports the skin barrier"},
    {"Ingredient": "farnesol", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Naturally occurring compound with antibacterial properties; helps reduce acne-causing bacteria and improve skin scent"},
    {"Ingredient": "cypress oil", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Astringent essential oil with antimicrobial properties; helps control excess oil but may irritate sensitive skin"},
    {"Ingredient": "sodium pca", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Natural humectant found in skin; helps maintain hydration and skin elasticity"},
    {"Ingredient": "sodium stearoyl lactylate", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Emulsifier and skin conditioner; helps improve texture and hydration without clogging pores"},
    {"Ingredient": "tamarind extract", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Natural extract rich in antioxidants and AHAs; gently exfoliates and hydrates the skin"},
    {"Ingredient": "willow bark extract", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Natural source of salicylic acid; gently exfoliates, unclogs pores, and reduces inflammation"},
    {"Ingredient": "lemon balm extract", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Calming botanical with antioxidant and antimicrobial properties; soothes irritated or acne-prone skin"},
    {"Ingredient": "cinnamon extract", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Potent botanical with antimicrobial properties; may irritate or sensitize skin if not used in low concentrations"},
    {"Ingredient": "peach kernel oil", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Light, nourishing oil rich in fatty acids and vitamins; moisturizes without clogging pores"},
    {"Ingredient": "calendula extract", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Soothing botanical extract with anti-inflammatory and healing properties; ideal for sensitive or irritated skin"},
    {"Ingredient": "octocrylene", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "UVB filter used in sunscreens; stabilizes other actives like avobenzone and provides water resistance"},
    {"Ingredient": "algae extract", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Mineral-rich marine extract that hydrates, detoxifies, and supports skin elasticity"},
    {"Ingredient": "kelp extract", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Seaweed extract packed with antioxidants and vitamins; helps soothe and protect the skin barrier"},
    {"Ingredient": "cucumber extract", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True,
     "Description": "Cooling and soothing botanical that calms irritation, hydrates, and refreshes skin"},
    {"Ingredient": "ylang ylang oil", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Floral essential oil with balancing and antimicrobial effects; may cause irritation on sensitive or acne-prone skin"},
    {"Ingredient": "chlorella extract", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Nutrient-dense algae extract that detoxifies, protects against pollution, and supports skin regeneration"},
    {"Ingredient": "azelaic acid", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Anti-inflammatory and brightening acid that treats acne, rosacea, and pigmentation while being gentle on skin"},
    {"Ingredient": "panthenol", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Pro-vitamin B5; deeply hydrating and soothing ingredient that supports skin barrier repair and reduces irritation"},
    {"Ingredient": "vitamin b5", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Pro-vitamin B5; deeply hydrating and soothing ingredient that supports skin barrier repair and reduces irritation"},
    {"Ingredient": "centella asiatica extract", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Soothing botanical known for healing, calming inflammation, and strengthening the skin barrier"},
    {"Ingredient": "snail mucin", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Hydrating and repairing ingredient rich in glycoproteins; supports cell regeneration and smooths skin"},
    {"Ingredient": "bakuchiol", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Natural retinol alternative; helps reduce fine lines and pigmentation without irritation"},
    {"Ingredient": "gluconolactone", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Gentle PHA exfoliant that hydrates while exfoliating; ideal for sensitive or dry skin"},
    {"Ingredient": "malic acid", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "AHA derived from apples; gently exfoliates, improves texture, and enhances skin radiance"},
    {"Ingredient": "trehalose", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Powerful sugar-based humectant; protects skin cells from dehydration and oxidative stress"},
    {"Ingredient": "resveratrol", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Potent antioxidant found in grapes; helps protect against environmental stress and signs of aging"},
    {"Ingredient": "carnitine", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Amino acid derivative that helps regulate sebum and improve skin texture; beneficial for oily and acne-prone skin"},
    {"Ingredient": "camellia oil", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Lightweight, antioxidant-rich oil that nourishes and softens skin without clogging pores"},
    {"Ingredient": "silver citrate", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Antimicrobial agent derived from silver; helps reduce acne-causing bacteria and soothe skin"},
    {"Ingredient": "tea seed oil", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Lightweight, antioxidant-rich oil that nourishes and softens skin without clogging pores"},
    {"Ingredient": "copper peptides", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Peptides combined with copper ions that promote skin regeneration, firming, and wound healing"},
    {"Ingredient": "beta-glucan", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Powerful soothing and moisturizing agent that supports the skin barrier and reduces sensitivity"},
    {"Ingredient": "beta glucan", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Powerful soothing and moisturizing agent that supports the skin barrier and reduces sensitivity"},
    {"Ingredient": "madecassoside", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Active compound from centella asiatica; calms inflammation, promotes healing, and strengthens the skin barrier"},
    {"Ingredient": "ethyl ascorbic acid", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Stable vitamin C derivative that brightens skin, supports collagen production, and protects against free radicals"},
    {"Ingredient": "hydroxyethyl urea", "Safety_Score": 10, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Excellent humectant that increases skin hydration and improves texture without clogging pores"},
    {"Ingredient": "caprylic", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Lightweight emollient derived from coconut oil and glycerin; helps smooth and soften skin without being greasy"},
    {"Ingredient": "capric triglyceride", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Lightweight emollient derived from coconut oil and glycerin; helps smooth and soften skin without being greasy"},
    {"Ingredient": "polysorbate 20", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Mild emulsifier and solubilizer derived from sorbitol; helps mix oil and water in formulations and is generally non-irritating"},
    {"Ingredient": "isopropyl myristate", "Safety_Score": 6, "Comedogenic": True,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": False, "Acne_Prone_Safe": False, "Description": "Emollient that enhances product absorption and smoothness, but highly comedogenic and not suitable for acne-prone skin"},
    {"Ingredient": "linalool", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Naturally occurring fragrance compound; can be sensitizing or irritating to sensitive or acne-prone skin"},
    {"Ingredient": "limonene", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Citrus-derived fragrance component; has antioxidant properties but can oxidize and irritate skin"},
    {"Ingredient": "citral", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Fragrance ingredient found in citrus oils; can be irritating to sensitive or compromised skin"},
    {"Ingredient": "geraniol", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Floral-scented fragrance compound; may cause sensitivity or allergic reactions in some skin types"},
    {"Ingredient": "eugenol", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Clove-derived fragrance component; has antimicrobial effects but may irritate sensitive skin"},
    {"Ingredient": "betaine", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Gentle sugar-derived humectant that hydrates, soothes, and helps protect the skin barrier"},
    {"Ingredient": "pentylene glycol", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Hydrating and antimicrobial agent that improves texture and enhances penetration of active ingredients"},
    {"Ingredient": "butylene glycol", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Common humectant and solvent that retains moisture, smooths skin, and improves product absorption"},
    {"Ingredient": "xylitol", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Sugar alcohol that acts as a humectant; hydrates the skin and helps improve barrier function"},
    {"Ingredient": "caprylyl glycol", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Moisturizing agent and preservative booster; hydrates while enhancing product stability"},
    {"Ingredient": "isocetyl stearate", "Safety_Score": 6, "Comedogenic": True,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": False, "Acne_Prone_Safe": False, "Description": "Emollient ester that softens skin and adds slip; may clog pores in oily or acne-prone skin"},
    {"Ingredient": "alkyl benzoate", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Lightweight emollient and texture enhancer; adds a silky feel and helps dissolve UV filters"},
    {"Ingredient": "behenyl alcohol", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Fatty alcohol used as an emollient and thickener; non-irritating and safe for sensitive skin"},
    {"Ingredient": "polyhydroxy acid", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Gentle exfoliant that hydrates and improves skin texture; ideal for sensitive or dry skin"},
    {"Ingredient": "gluconic acid", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Mild acid with exfoliating and antioxidant properties; improves hydration and skin clarity"},
    {"Ingredient": "succinic acid", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Natural acid with antimicrobial and anti-inflammatory effects; helps reduce acne and excess oil"},
    {"Ingredient": "mulberry extract", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Brightening botanical rich in antioxidants; helps reduce pigmentation and improve skin tone"},
    {"Ingredient": "houttuynia cordata extract", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Anti-inflammatory and antibacterial plant extract; soothes irritation and helps control acne"},
    {"Ingredient": "disodium edta", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Chelating agent that improves product stability by binding metal ions; generally safe and non-irritating"},
    {"Ingredient": "hydroxyacetophenone", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Synthetic antioxidant and soothing agent; helps calm skin and improve product preservation"},
    {"Ingredient": "sodium gluconate", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Salt of gluconic acid; used as a chelator and skin-conditioning agent; helps balance formulation pH"},
    {"Ingredient": "tranexamic acid", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Brightening agent that targets dark spots and hyperpigmentation; suitable for sensitive and acne-prone skin"},
    {"Ingredient": "ectoin", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "A stress-protection molecule that hydrates, soothes, and strengthens the skin barrier; ideal for sensitive skin"},
    {"Ingredient": "azulene", "Safety_Score": 9, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Anti-inflammatory compound derived from chamomile; calms redness and irritation, especially in sensitive or inflamed skin"},
    {"Ingredient": "bio-retinol", "Safety_Score": 8, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Plant-based retinol alternative that boosts collagen, smooths texture, and reduces signs of aging with less irritation"},
    {"Ingredient": "benzyl alcohol", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Preservative and solvent with mild antibacterial properties; can be irritating in high concentrations"},
    {"Ingredient": "hexyl cinnamal", "Safety_Score": 6, "Comedogenic": False,
     "Dry_Skin_Safe": False, "Oily_Skin_Safe": True, "Acne_Prone_Safe": False, "Description": "Fragrance compound with floral scent; may cause allergic reactions or irritation in sensitive skin"},
    {"Ingredient": "methylparaben", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Common preservative used to prevent microbial growth; generally safe in low concentrations but debated for long-term use"},
    {"Ingredient": "propylparaben", "Safety_Score": 7, "Comedogenic": False,
     "Dry_Skin_Safe": True, "Oily_Skin_Safe": True, "Acne_Prone_Safe": True, "Description": "Common preservative used to prevent microbial growth; generally safe in low concentrations but debated for long-term use"}

]

# Save it to a JSON file
with open("ingredient_data.json", "w", encoding="utf-8") as f:
    json.dump(ingredient_data, f, indent=4)

print("✅ Dataset saved to ingredient_data.json")
